require "fileutils"

module Workflows
  module Compilers
    # Produces a thin generated Minitest system-test file that delegates to
    # Workflows::Runner::TestMode. The generated file is checked into the
    # host app's test/system/workflows/ tree so failures surface in the
    # standard test output and git diffs show workflow changes.
    module SystemTest
      module_function

      def call(workflow)
        class_name = class_name_for(workflow.name)
        <<~RUBY
          # This file is generated by `bin/rails workflows:compile_tests`.
          # Do not edit by hand — edit the source workflow YAML instead:
          #   config/workflows/#{workflow.name}.yml
          require "application_system_test_case"

          class #{class_name} < ApplicationSystemTestCase
            test "#{workflow.name}" do
              Workflows::Runner::TestMode.new("#{workflow.name}").run(self)
            end
          end
        RUBY
      end

      def write_to(workflow, test_root:)
        path = File.join(test_root, "workflows", "#{workflow.name}_test.rb")
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, call(workflow))
        path
      end

      def class_name_for(workflow_name)
        # "teacher/grade_assignment" -> "Workflows::Teacher::GradeAssignmentTest"
        parts = workflow_name.to_s.split("/").map { |p| p.split("_").map(&:capitalize).join }
        "Workflows::" + parts.join("::") + "Test"
      end
    end
  end
end
