require "fileutils"

module Workflows
  module Compilers
    # Produces a thin generated Minitest system-test file that delegates to
    # Workflows::Runner::TestMode. The generated file is checked into the
    # host app's test/system/workflows/ tree so failures surface in the
    # standard test output and git diffs show workflow changes.
    module SystemTest
      module_function

      def call(workflow)
        parts = workflow.name.to_s.split("/").map { |p| p.split("_").map(&:capitalize).join }
        leaf  = parts.pop + "Test"
        # Emit nested `module` blocks so the generated file defines
        # intermediate constants (Workflows::Teacher, etc.) without requiring
        # the host app to register them ahead of time.
        module_chain = ["Workflows"] + parts
        indent = lambda { |n| "  " * n }
        opening = module_chain.each_with_index.map { |m, i| "#{indent.call(i)}module #{m}" }.join("\n")
        closing = module_chain.each_with_index.map { |_, i| "#{indent.call(module_chain.size - 1 - i)}end" }.join("\n")
        body_indent = indent.call(module_chain.size)

        <<~RUBY
          # This file is generated by `bin/rails workflows:compile_tests`.
          # Do not edit by hand — edit the source workflow YAML instead:
          #   config/workflows/#{workflow.name}.yml
          require "application_system_test_case"

          #{opening}
          #{body_indent}class #{leaf} < ApplicationSystemTestCase
          #{body_indent}  # `fixtures :all` in host test_helpers wipes the users/accounts
          #{body_indent}  # that the demo seed created, so we re-seed before each run.
          #{body_indent}  # DemoSchool.call is idempotent.
          #{body_indent}  setup do
          #{body_indent}    Workflows::Seed::DemoSchool.call(host: "#{workflow.host}") if defined?(Workflows::Seed::DemoSchool)
          #{body_indent}  end

          #{body_indent}  test "#{workflow.name}" do
          #{body_indent}    Workflows::Runner::TestMode.new("#{workflow.name}").run(self)
          #{body_indent}  end
          #{body_indent}end
          #{closing}
        RUBY
      end

      def write_to(workflow, test_root:)
        path = File.join(test_root, "workflows", "#{workflow.name}_test.rb")
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, call(workflow))
        path
      end

      def class_name_for(workflow_name)
        # "teacher/grade_assignment" -> "Workflows::Teacher::GradeAssignmentTest"
        parts = workflow_name.to_s.split("/").map { |p| p.split("_").map(&:capitalize).join }
        "Workflows::" + parts.join("::") + "Test"
      end
    end
  end
end
